# Project information
site_name: 'Helios4 Wiki'
site_description: 'Helios4 Wiki'
site_author: 'Kobol Team'
site_url: 'https://wiki.kobol.io'

# Repository
repo_name: 'Helios4 GitHub Repo'
repo_url: 'https://github.com/helios-4'

# Copyright
copyright: 'Copyright &copy; Kobol Team 2017'

# Documentation and theme
theme:
  name: 'material'
  favicon: './img/favicon.png'
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Options
extra:
  logo: './img/helios4_logo.png'
  social:
    - type: 'home'
      link: 'https://kobol.io/helios4'
    - type: 'github'
      link: 'https://github.com/helios-4'
    - type: 'facebook'
      link: 'https://facebook.com/kobol.io'
    - type: 'rss-square'
      link: 'https://blog.kobol.io'

# Google Analytics
google_analytics:
  - 'UA-96982596-2'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)


pages:
- Introduction: 'index.md'
- Hardware: 'hardware.md'
- Software:
  - U-Boot : 'uboot.md'
  - Kernel : 'kernel.md'
  - Linux : 'linux.md'
  - OpenMediaVault : 'omv.md'
  - Syncloud : 'syncloud.md'
- Starter kit : 'kit.md'
- Download: 'download.md'
- Install: 'install.md'
- Development: 'dev.md'
- Documents: 'docs.md'
- About: 'about.md'
